title: Stork Chat
tagline: Chat with a midwife. Anytime, anywhere.
description: We believe the best care for pregnancy is a woman's voice. We want to empower every woman and baby in the world to have autonomy with safe and quick access to a maternal healthcare professional.
url: https://storkchat.co.uk

logo: /images/logo.png
backgroundImage: /images/background-doodles.png

mailchimpURI:
mailchimpAntiSpamCode:

showPrivacyPolicy: false

socialMediaImage: /images/logo.png
twitter: storkchat
facebook: storkchat
instagram: storkchat

forkMeOnGithub: false #se this false to remove fork me on github ribbon
